/*import type { Metadata } from "next";*/
import "./globals.css";
import { ReactNode } from "react";

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

/*export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}*/

const RootLayout = async ({ children }: { children: ReactNode }) => {
	return (
		<html>
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
